/* Generated By:JavaCC: Do not edit this line. DMOZBNFParserConstants.java */
package it.unitn.disi.nlptools.components.parsers.controlled.dmozparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DMOZBNFParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INDEX_SEPARATOR = 7;
  /** RegularExpression Id. */
  int INDEX = 8;
  /** RegularExpression Id. */
  int NN = 9;
  /** RegularExpression Id. */
  int NNS = 10;
  /** RegularExpression Id. */
  int VBG = 11;
  /** RegularExpression Id. */
  int JJ = 12;
  /** RegularExpression Id. */
  int VBN = 13;
  /** RegularExpression Id. */
  int CC = 14;
  /** RegularExpression Id. */
  int COMMA = 15;
  /** RegularExpression Id. */
  int IN = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"/\"",
    "\"\\r\\n\"",
    "\"|\"",
    "<INDEX>",
    "<NN>",
    "<NNS>",
    "<VBG>",
    "<JJ>",
    "<VBN>",
    "<CC>",
    "<COMMA>",
    "<IN>",
  };

}
